<footer>
    <div class="bottom">
    <ul>
      <li><p>サイトマップ</p></li>
        <li>農園について</li>
        <li>栽培方法</li>
        <li>クラウドファンディング</li>
        <li>歴史</li>
        <li>発足経緯</li>
      </ul>
      <ul>
        <li>ECサイト</li>
        <li>種類販売</li>
      </ul>
      <ul>
        <li>調理例</li>
        <li>惣菜</li>
        <li>お菓子</li>
        <li>調味料</li>
      </ul>
      <ul>
        <li>お知らせ</li>
        <li>直販売</li>
        <li>提携レストラン</li>
        <li>Blog</li>
      </ul>
  </div>
      <small>
      <p>商品取引商法</p>
      <p>プライバシーポリシー</p>
      <p>コピーライト</p>
      </small>
  </footer>